### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by JohnCoene** [RinteRface/shinybulma#12]
I'm using shinybulma for [echarts4r shiny demo](https://shiny.john-coene.com/echarts4rShiny/) and noticed that the container has no effect if, as described in the [official docs](https://bulma.io/documentation/layout/container/), it is not a child of:

- `navbar`
- `hero`
- `section`
- `footer`

Though it's fine if one is aware it's rather counter-intuitive for the regular Shiny user, perhaps section should automatically add a container?

**Comment by DivadNojnarg** [comment]
What do you suggest:
- we remove the bulma-container function and add a container to the section (but need to update all examples accordingly)
- we keep the container function but add a container tag to the section.

**Comment by JohnCoene** [comment]
Well, I'm personally unsure. I think keeping them separate is good in the event a user does not want a container. Perhaps adding an argument `container` which defaults to `TRUE` in `bulmaSection`? What do you reckon?

**Comment by JohnCoene** [comment]
Great! I'll take of it.

**Comment by JohnCoene** [comment]
Done.
