### ISSUE TITLE
Several css classes not available due to old bulma version

### ISSUE THREAD

**Issue by thothal** [RinteRface/shinybulma#23]
The `bulma` framework introduced several new classes in newer version. Currently `shinybulma` uses [version 0.7.2](https://github.com/RinteRface/shinybulma/blob/44bfb0d8d259f0ecd24bf91da25cdde3189d07db/R/deps.R#L16). Thus, features such as: `is-family-*` or `spacing helpers` are not available.

Can we change the `CSS` to a more recent version? Any reasons not to do yo? Ideally we would use the newest version to include all the features, but maybe that is a too drastic change and at least `0.7.4` to allow for the `is-family-*` classes? 

Your thoughts?

**Comment by JohnCoene** [comment]
I just pushed an updated version of the CSS

**Comment by thothal** [comment]
Hm, I saw that you updated the css files of the themes which are in the repo (thanks), while the main bulma css (which is loaded from a cdn) still uses an old version (0.7.2. cf to the linked line in code in the issue). That is, things which are covered in the themes work now, while others (which are solely in the master bulma won't).

Compare [this fiddle](https://jsfiddle.net/xjqs8k9h/) with the output of:

```r
library(shinybulma)
library(shiny)

ui <- bulmaPage(bulmaSection(p("This text is code style", 
                               class = "is-family-code has-background-danger p-6 has-text-white")))

shinyApp(ui, function(...) {})
```

While the new `is-family-code` is properly displayed (I guess it also part of the themes css), the `p-6` (the padding modifyer) does not work (I guess it is only in the master bulma css)

## Fiddle Screenschot
![Bulma_new](https://user-images.githubusercontent.com/30824940/95961918-0320b580-0e06-11eb-8ed1-2b2f554a1c52.PNG)

## Shinybulma Screenshot

![Bulma_old](https://user-images.githubusercontent.com/30824940/95961938-0c118700-0e06-11eb-91e2-95a4e8d94789.PNG)


# Remedy

Update also the master bulma dependency in [deps.R](R/deps.R)

**Comment by JohnCoene** [comment]
Sorry, I omitted that: should be good now; the snippet you shared worked fine on my end.
