### ISSUE TITLE
shinyWidgets::pickerInput() do not work under the bulmaPage()

### ISSUE THREAD

**Issue by hm-yuan** [RinteRface/shinybulma#36]
Thanks for this awesome template! 
I find some widgets in shinyWidgets do not work under the `shinybulma`, such as the shinyWidgets::pickerInput(), withwhich I want to make multiple selections. I wonder do any solutions can be taken to solve the problem?

**Comment by quciet** [comment]
Hi there,

shinybulma is indeed awesome! I'm having the same question here and am wondering if this is related to the answer under this issue #16 

@hm-yuan What did you end up doing?  

Thanks!
